[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13.5"
actix-cors = "0.7.1"
actix-web = "4.11.0"
actix-ws = "0.3.0"
axum = "0.8.6"
pnet = "0.35.0"
serde = "1.0.228"
serde_json = "1.0.145"
sled = "0.34.7"
tokio = "1.48.0"
